### ISSUE TITLE
Azure: Perfkit VNets overwrite ExpressRoute settings

### ISSUE THREAD

**Issue by timothyeharris** [GoogleCloudPlatform/PerfKitBenchmarker#122]
I have a service account that runs ExpressRoute for connectivity to my corporate network.  I decided to run PerfKitExplorer to test out various Azure VM Sizes and Regions.  My assumption was that since PerfkitBenchmarker was setting up its own affinity groups and VNets, that I'd have complete isolation.  Unfortunately, it appears that when the network configuration file is being parsed to add new virtual networks to the service account, PerfkitBenchmarker is dropping the ExpressRoute configuration information off... so when it stands up new virtual networks, it destroys ExpressRoute connectivity (and takes out corporate connectivity to Azure resources as a consequence) :-(

**Comment by timothyeharris** [comment]
![networkconfig](https://cloud.githubusercontent.com/assets/11050091/6236477/bb8d9ed6-b69f-11e4-94a4-f23c57da36a5.PNG)

**Comment by voellm** [comment]
PKB creates all new service and network objects and deletes them when
done.  Do you think this is a bug for PKB or AZURE?

On Tue, Feb 17, 2015 at 12:23 PM, timothyeharris <notifications@github.com>
wrote:

> [image: networkconfig]
> <https://cloud.githubusercontent.com/assets/11050091/6236477/bb8d9ed6-b69f-11e4-94a4-f23c57da36a5.PNG>
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/122#issuecomment-74745233>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by timothyeharris** [comment]
I believe it's a PKB bug. (That said, I think the way Azure updates VNets is less than ideal).

The network configuration for an entire Azure service account is contained in the network configuration file.  This defines all the network information for all the locations, affinity groups, etc.  The script command "Set-AzureVNetConfig" merely replaces the existing network configuration with a new one.

To correctly *update* the network information to add a new affinity group and virtual network, you need to use the "Get-AzureVNetConfig" command to download the existing configuration XML file, then walk the file to add the desired virtual network site information (without disturbing the rest of the configuration) and then use the "Set-AzureVNetConfig" command to update the configuration.

Deleting the Virtual Network Sites you add is just reversing the process.

It's unfortunate that there is no "AddVNet" and "DeleteVNet" command (like there are for VMs)... The fact that Azure has a "global" config file for this is a little scary - especially if you're the one tasked with maintaining it :-) 

Unless PKB undertakes the process of *updating* a service account's existing network configuration, you'll end up with more people blowing away their networking configurations like I did --- except possibly on a much larger scale (and possibly without their configuration backed up).

https://msdn.microsoft.com/en-us/library/azure/jj152898.aspx

https://msdn.microsoft.com/en-us/library/azure/jj152828.aspx

The other option is to put a giant warning out telling people not to run PKB on production Azure Service Accounts :-)

**Comment by timothyeharris** [comment]
Ok - I dug a little deeper and found that there is an Add and Delete command in the tools for Linux: 

http://azure.microsoft.com/en-us/documentation/articles/command-line-tools/#Commands_to_manage_vnet

This is more advanced than what is provided in PowerShell (and I assume is what PKB is using).

So -- this indicates it's more likely a bug in the Azure Command Line Tools for Linux....

**Comment by voellm** [comment]
Tim,

Thanks for digging into this.  Very helpful.

Would like you to make a proposed fix?  If not I can assign the bug to
someone on my team - likely ehankland since he did a lot of this code - to
fix.

  Tony


On Tue, Feb 17, 2015 at 5:42 PM, Tim Harris <notifications@github.com>
wrote:

> Ok - I dug a little deeper and found that there is an Add and Delete
> command in the tools for Linux:
>
>
> http://azure.microsoft.com/en-us/documentation/articles/command-line-tools/#Commands_to_manage_vnet
>
> This is more advanced than what is provided in PowerShell (and I assume is
> what PKB is using).
>
> So -- this indicates it's more likely a bug in the Azure Command Line
> Tools for Linux....
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/122#issuecomment-74795253>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by timothyeharris** [comment]
Tony - coding it up goes beyond my skill level I'm afraid.

**Comment by voellm** [comment]
Happy to get it fixed for you.

**Comment by timothyeharris** [comment]
Awesome, thanks :-)  I'm happy to test any fixes.

**Comment by ehankland** [comment]
Like Tim mentioned, we are using the create/delete commands in the Azure cli for linux. Unfortunately it looks like those commands will overwrite any more advanced configuration that you may have already set up (arguably a bug with the linux cli). There are export/import commands that more closely match up with the powershell version, so adding a workaround should be feasible. That said, using the export/update/import strategy has the potential to badly mess up the configuration if there are multiple processes trying to update the config at the same time without adding some kind of global locking (e.g. via cloud storage) - the cli was taking care of this for us. Doing this ourselves would introduce the additional failure mode where a process acquires the global lock and then gets killed before being able to clean it up, preventing any other perfkit processes from running on Azure until the user cleans up the object (and still leaves us open to the user manually messing with the config and ignoring the lock). I don't like the extra complexity that this would add - I'd rather do something simpler like provide the option to use the export/import commands but warn the user not to run any other Perfkit processes or update the config until it finishes running. Does anyone have any strong opinions about what the fix should be (ideally I'd prefer the cli being updated so that this workaround wasn't necessary, but I don't know what the time frame on that would be)?

**Comment by timothyeharris** [comment]
All - I spoke to some folks in Azure Engineering who told me they're tracking a bug against the x-plat CLIs here: https://github.com/Azure/azure-xplat-cli/issues/1569.  I'll do some more reading, but it looks like they may have just merged fixes for this issue.

**Comment by voellm** [comment]
Thanks Tim for staying with this issue.  Glad it is getting addressed.
We'll keep the bug open until the azure CLI tool is updated.

On Mon, Feb 23, 2015 at 3:37 PM, Tim Harris <notifications@github.com>
wrote:

> All - I spoke to some folks in Azure Engineering who told me they're
> tracking a bug against the x-plat CLIs here: Azure/azure-xplat-cli#1569
> <https://github.com/Azure/azure-xplat-cli/issues/1569>. I'll do some more
> reading, but it looks like they may have just merged fixes for this issue.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/issues/122#issuecomment-75662216>
> .
>



-- 
Anthony F. Voellm (aka Tony)
Google Voice:  (650) 516-7382
<https://www.google.com/voice/b/0?pli=1#phones>
Blog: http://perfguy.blogspot.com/

**Comment by voellm** [comment]
Any update here?

**Comment by timothyeharris** [comment]
I just checked and it appears the fix is committed for release 0.8.16 of the Azure CLI tools.  The current release is 0.8.15 -- so as yet, the fix is not released.

**Comment by ehankland** [comment]
The current version is now 0.9.3 so this should be fixed.
