### ISSUE TITLE
Don't print full usage on usage error

### ISSUE THREAD

**Issue by gareth-ferneyhough** [GoogleCloudPlatform/PerfKitBenchmarker#1261]
If a user provides an invalid flag to `pkb.py`, it prints a usage error along with all the valid flags. This makes it difficult for the user to see what the actual error was, as he/she must scroll up through the usage instructions to find the error.

It would be better to print minimal usage instructions when the user passes invalid flags, so that the error is clearly visible.

**Comment by tedsta** [comment]
+1

**Comment by meteorfox** [comment]
Also, it would be nice to be able to selectively print the flags info for a particular sub-module (e.g. provider, benchmarks, pkb flags, packages, etc) instead of the wall of text.

Something like `pkb.py --help=perfkitbenchmarker.provders.gcp` which would only show the flags of all the submodules matching the string `perfkitbenchmarker.provders.gcp`, and possibly the string could be a regexp.

Looks like the either method `FLAGS.ModuleHelp(module)`[1] or use one of the internal dicts in gflags that maps module names to a list of flags might do the trick.

[1] https://github.com/google/python-gflags/blob/master/gflags/flagvalues.py#L914-L925

**Comment by meteorfox** [comment]
I have a POC for my suggestion #1268 PTAL

**Comment by gareth-ferneyhough** [comment]
Thanks! I'll take a look early next week.
