### ISSUE TITLE
Single benchmark issue with GCloud CLI

### ISSUE THREAD

**Issue by w3st3ry** [GoogleCloudPlatform/PerfKitBenchmarker#1739]
Hello there,

I've set and init my gcloud current project as usual. I run the single benchmark with right configuration and project ID. 
Then I get this error message with an depreciate command on `gcloud CLI` apparently.

Error:
```
2018-07-27 11:03:15,962 8a514f14 Thread-2 iperf(1/1) vm_util.py:321 INFO     Ran gcloud compute networks create pkb-network-8a514f14 --format json --quiet --project manawa-20009664 --mode auto. Got return code (2).
STDOUT:
STDERR: ERROR: (gcloud.compute.networks.create) `mode` has been removed. Please use `subnet-mode` instead.
Usage: gcloud compute networks create NAME [optional flags]
  optional flags may be  --bgp-routing-mode | --description | --help | --mode |
                         --range | --subnet-mode

For detailed information on this command and its flags, run:
  gcloud compute networks create --help
```

After that PerfKit try to run that in loop but nothing change...

I use the latest release `1.13.0`, is it normal? Maybe I could create that manually and force with a flag?

Thanks in advance 👍

**Comment by dlott** [comment]
Hi w3st3ry,

It looks like that has been fixed in head (https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/commit/2db3b2125d884ef0153be0a9c04e55ea5335bc09), but we haven't cut a new release since then.  You can either run PKB from head (recommended) or roll gcloud back to a version which supports `mode`.
