### ISSUE TITLE
Trying to run cassandra_ycsb on my local machine using static config YAML file.

### ISSUE THREAD

**Issue by adnavare** [GoogleCloudPlatform/PerfKitBenchmarker#1820]
Hi Folks,

I am trying to run cassandra_ycsb benchmark on my local machine without any cloud provisioning with static config YAML file. Here is the config file https://pastebin.com/qRw6Jfed 
I am running as sudo ./pkb.py --benchmarks=cassandra_ycsb --benchmark_config_file=../my_config_file.yaml

But I am seeing OSError followed by one another error, not clear it is because of what. Python2.7 is installed on my machine, SSH access is enabled to the user. Could you please provide some pointers. 
Here is the error https://pastebin.com/pzV3FEtT

**Comment by adnavare** [comment]
After debugging a little, I see when PKB is running, different processes try to access dpkg and are unable to get the lock. Is it not possible to run PerfKit on the a machine which act as the same machine for the workload? I am deploying PerfKit on my Ubuntu machine 18.10 and trying to run cassandra_ycsb on the same machine. If it is not possible, is there a way/tweak to do that?

**Comment by yuyantingzero** [comment]
Hi adnavare,

If the error is caused by installing package concurrently. 
You can preinstall the packages for the test and add:
install_packages: false
(Example in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker#advanced-how-to-run-benchmarks-without-cloud-provisioning-eg-local-workstation)
To install package manually, read how each package is installed and copy-paste the command and run manually.

Alternatively, by reading code in https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_benchmarks/cassandra_ycsb_benchmark.py#L143
Seems like if you set --ycsb_client_vms=0, it will force to use same vm to run both cassandra and ycsb, install packages sequentially and avoid the race condition.

**Comment by adnavare** [comment]
@yuyantingzero : Thanks for the reply. I have switched to using two machine setup, one that act as a controller + client i.e. YCSB runs on this machine and the other one as a server a.k.a worker. I am able to run MongoDB with this setup but cassandra is still giving me OSError: No such file or directory?
Does it need any specific format for the config file?

**Comment by yuyantingzero** [comment]
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/blob/master/perfkitbenchmarker/linux_benchmarks/cassandra_ycsb_benchmark.py#L63
Seems like by default, cassandra_ycsb try to use 3 server vms for replication purpose, which is why PKB try to create additional VMs on GCP (default cloud provider) and run into errors. (You probably didn't have gcloud setup correctly)

Given you only have a single machine. Try set --num_vms=1 and --cassandra_replication_factor=1 to disable replication.

**Comment by adnavare** [comment]
@yuyantingzero : Ah okie, good to know. So now I have two VMs here https://pastebin.com/Vv7sDu9H, so I should mention --num_vms=2? I saw cassandra also follows workers, and clients naming convention so I have one worker and one client

**Comment by yuyantingzero** [comment]
The naming is confusing. As far as i understand:
num_vms -> cassandra vms (workers)
ycsb_client_vms -> ycsb vms (clients)

In your case, --num_vms=1 to use vm1 as cassandra vm. (num_vms=2 will resulting creation of a cloud VM)

**Comment by adnavare** [comment]
@yuyantingzero : Ah I see, gotcha. Yes with --num_vms=2, it again tried to create on GCP which does not exist. With --num_vms=1, it went pass that OSError. I will update whether it completes the run or not. Thank you so much

**Comment by adnavare** [comment]
Somehow the process is getting stuck while dowloading 0.9.0 version of YCSB, it is taking more than 15 minutes to download the tar file, which should not be the case. I tried to download using the same command outside of the process, and it gets downloaded pretty quickly. 
I am running using the command "./pkb.py --benchmarks=cassandra_ycsb --bencharmark_config_file=baremetal-static.yaml --num_vms=1 --cassandra_replication_factor=1". This is correct right?

**Comment by adnavare** [comment]
I was able to surpass that error by trying 0.11.0 version of YCSB, but now it is failing to download http://archive.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.gz  and throwing "Connection Timeout". Outside of the process I am running the exact same command, and I can download that. Do we have to specify proxy somewhere in the configuration?

**Comment by yuyantingzero** [comment]
"specify proxy" not that i know  of.

It sounds like ssh issue to me. One thing you could try is rerunning the ssh command which leads to the failure in your terminal, instead of running wget directly.

The command should look like:
ssh -A -p 22 user@host -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAuthentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i your_key mkdir -p /opt/pkb && cd /opt/pkb && wget archive.apache.org/dist/ant/binaries/apache-ant-1.9.6-bin.tar.gz && tar -zxf apache-ant-1.9.6-bin.tar.gz && ln -s /opt/pkb/apache-ant-1.9.6/ /opt/pkb/ant

**Comment by adnavare** [comment]
Looks like something wrong is happening when executed that command with RemoteCommand()

**Comment by adnavare** [comment]
@yuyantingzero Is it somehow possible to share my screen with you in some way, may be google hangout?
I am running Ubuntu 18.10
The client machine is different - it is Ubuntu 16.04, server machine is different running 18.10
Somehow on the client machine, inside /opt/pkb/ I see ycsb and ant-x-x-x.tar.gz
I was looking at the other issue #1823 and mine looks exactly the same.
Snippet  looks like this https://pastebin.com/5VqDZdeN 

Is there a way I can share my screen, may be google hang out?

**Comment by adnavare** [comment]
Weird thing is, I can run MongoDB but not Cassandra. And the way PrepareServer and PrepareClient is executed in MongoDB is the same way it is in Cassandra.

**Comment by adnavare** [comment]
I think I will open a new issue, as the issue with local machine has been resolved, for which I opened this
