### ISSUE TITLE
Does PerfKitBenchmarker-1.14.0 support local workstation testing for Hadoop terasort case?

### ISSUE THREAD

**Issue by xianlaishen2** [GoogleCloudPlatform/PerfKitBenchmarker#2241]
Hi 
I want to use PerfKitBenchmarker tool to test Hadoop terasort case for aarch64(ARM64 server) and x86_64(sm6148) performance comparison. After studied the README.md document of PerfKitBenchmarker latest version(1.14.0) and PerfKitBenchmarker source codes, found out the default case hadoop_terasort_benchmark.py example is used to test GCP cloud(configuration is for GCP).
Does PerfKitBenchmarker support local workstation testing for Hadoop terasort case(Pseudo-Distributed Operation mode, not cluster mode)? If it can, can you provide PerfKitBenchmarker configuration guidance documents for testing the local workstation(better for Hadoop teraport case)?
Thanks very much.

Xianlai Shen

**Comment by pmkc** [comment]
PerfKitBenchmarker supports neither pseudo distributed Hadoop nor local workstation testing.

Pseudo distributed Hadoop is a reasonable feature request that would be good to support.

As for local testing, as you note PKB is designed to benchmark public cloud VMs not local servers. You can try to hack it by providing a "static virtual machine" with 127.0.0.1 as the IP and SSH into your local workstation, but you might hit weird edge cases.

It would be simple to simply [follow the steps for pseudo distributed Hadoop](https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-common/SingleCluster.html#Pseudo-Distributed_Operation) yourself and then measure the runtime of terasort.

If you would like to repurpose this FR to track single node Hadoop (on public clouds), I would be happy to edit it as such, but otherwise I will close it.

**Comment by xianlaishen2** [comment]
Hi pmkc,
I understand, please close the issue.
Thank you very much!

Best Wishes！
Xianlai Shen
