### ISSUE TITLE
GCP provider; disable creating new VPC for benchmarks

### ISSUE THREAD

**Issue by salmr0** [GoogleCloudPlatform/PerfKitBenchmarker#2902]
Is there a way to disable the creation of a new VPC for some of the benchmarks?  Can we instead pass in a VPC that already exists for use with the benchmarks?  Some projects/users may not have permission to create VPCs.

**Comment by shyamsabhaya** [comment]
For GCP, you can specify a network name, and it will use that network. It does create subnets for the VMs. I do not believe it creates any VPCs.

I believe AWS creates a VPC per VM. We do not have a feature/flag to pass in a VPC name instead of creating a new one when a VM is created. And I don't think there is any planned work for it. An implementation for this would be to add a flag in aws_network that passes in the name for VPCs and checks to see if it should use the VPC for the VM instead of creating a new one.

**Comment by shyamsabhaya** [comment]
Sorry. I was initially confused by the question. We have a flag that you can pass to specify the VPC.

`gce_network_name` can be set to set it to a predefiend VPC in GCP.

**Comment by salmr0** [comment]
Thanks adding `--gce_network_name=vpc_name` seems to have worked.  Now it is stuck trying to create a firewall rule to allow SSH access.  Is there a way to disable creating the SSH Firewall rule.  I do not need to do that for my use case.  I can already SSH into my project no need to create the firewall rule.

**Comment by dlott** [comment]
Have you tried `---gce_remote_access_firewall_rule`?
