### ISSUE TITLE
Standardize VM count metadata

### ISSUE THREAD

**Issue by cmccoy** [GoogleCloudPlatform/PerfKitBenchmarker#296]
Benchmarks utilizing a variable number of VMs are currently responsible for reporting the number of VMs used. We should create a single location to add this information to the metadata, under a fixed key.

**Comment by voellm** [comment]
Agreed.  We should start by adding a consistent label to all benchmarks - really all.  In this case I dont think we need to deprecate the old labels on specific benchmarks because it is not confusing like we did with the server_machine vs receiving_machine labels for the network benchmarks.

I'm advocating for "all" benchmarks to have the label even if they one use 1 VM like Spec CPU 2006.  This will make it easier to write a well specific query - ie ooking for the vm_count=1 vs absence of the vm_count label.  By the way I'm not saying vm_count should be the label name.

**Comment by ehankland** [comment]
Fixed by above PR
