### ISSUE TITLE
Long pkb tests time out on AWS Cloud Shell

### ISSUE THREAD

**Issue by rohanshetty10** [GoogleCloudPlatform/PerfKitBenchmarker#2979]
I run the AWS Benchmarking tests from the AWS Cloud Shell which works great for most tests but running long tests like unixbench, block_storage_workload, etc. lead to the Cloud shell timing out if it is running in the background. On reconnecting to the Cloud Shell the test progress is lost and all resources created by PKB are left running until terminated manually. 
Command used to run the test:
`./pkb.py --cloud=AWS --machine_type=<Machine_type> --benchmarks=<Test_name> --zone=us-west-1b`

I know it's not an issue with the Perfkit Benchmarker tool but is there a better way to test for running these long tests on AWS? Running the test in the foreground is not really possible for tests that take a couple of hours. I am little new to AWS so sorry if there is a simpler solution to this issue.
Any help or advice is appreciated. Thanks!

**Comment by dlott** [comment]
I haven't used AWS Cloud Shell, but this seems expected based on https://docs.aws.amazon.com/cloudshell/latest/userguide/limits.html#session-lifecycle-limitations
> Shell sessions
> * Inactive sessions: AWS CloudShell is an interactive shell environment—if you don't interact with it using your keyboard or pointer for approximately 20–30 minutes, your shell session will end. (Running processes do not count as interactions.)
> 
> * Long-running sessions: A shell session that's been running continuously for approximately 12 hours will automatically end, even if the user is regularly interacting with it during that period.

You should be able to run PKB on your local machine.  Or another VM in AWS to get around these limitations.  You'll have to make sure that the AWS CLI is properly configured in either case.

Since this isn't a PKB issue, I'm going to close this.
