### ISSUE TITLE
Help required regarding , running Object_storage_service  benchmark in Openstack Private Environment

### ISSUE THREAD

**Issue by debabhatt** [GoogleCloudPlatform/PerfKitBenchmarker#654]
Hi!  I was trying to run object_storage_service  benchmark  in a private openstack setup with  a static_vm_file

./pkb.py --cloud="OpenStack" --scratch_disk_type=standard --scratch_disk_size=10 --benchmarks="object_storage_service"  --object_storage_credential_file=/root/PerfKitBenchmarker   --static_vm_file=$server_info.json

the error i came over is as follows : 

2015-11-18 23:27:53,384 398d70ad MainThread object_storage_service(1/1) ERROR    Error during benchmark object_storage_service
Traceback (most recent call last):
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 297, in RunBenchmark
    DoPreparePhase(benchmark, benchmark_name, spec, detailed_timer)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/pkb.py", line 211, in DoPreparePhase
    benchmark.Prepare(spec)
  File "/root/PerfKitBenchmarker/perfkitbenchmarker/benchmarks/object_storage_service_benchmark.py", line 933, in Prepare
    FLAGS.boto_file_location)
MissingObjectCredentialException: ('Boto file cannot be found in %s but it is required for gcs or s3.', '/root/.boto')

so how to create .boto for openstack swift to run object_storage_service     benchmark  in an Openstack environment  .  

Any help will be greatly appreciated. 

Thanks .

**Comment by voellm** [comment]
OpenStack does not have an object store so you have to use one that is available.  PKB supports today Google Cloud Storage (GCS), Amazon S3 and Azure Blobs.

You select the object store using this flag "--storage=GCP"

If you want to use one of these object stores you will need to have an account with that could provider and have set up the CLI as described in the README.

In your particular cause the error is saying that there is no .boto file with credentials.  Here are the instructions for setting that up from the README...

Create and Configure a .boto file for object storage benchmarks
In order to run object storage benchmark tests, you need to have a properly configured ~/.boto file.

Here is how:
Create the ~/.boto file (If you already have ~/.boto, you can skip this step. Consider making a backup copy of your existing .boto file.)
To create a new ~/.boto file, issue the following command and follow the instructions given by this command:

$ gsutil config
As a result, a .boto file is created under your home directory.

Open the .boto file and edit the following fields:
In the [Credentials] section:
gs_oauth2_refresh_token: set it to be the same as the refresh_token field in your gcloud credential file (~/.config/gcloud/credentials), which was setup as part of the gcloud auth login step.

aws_access_key_id, aws_secret_access_key: set these to be the AWS access keys you intend to use for these tests, or you can use the same keys as those in your existing AWS credentials file (~/.aws/credentials).

In the [GSUtil] section:
default_project_id: if it is not already set, set it to be the google cloud storage project ID you intend to use for this test. (If you used gsutil config to generate the .boto file, you should have been prompted to supply this information at this step).

In the [OAuth2] section: client_id, client_secret: set these to be the same as those in your gcloud credentials file (~/.config/gcloud/credentials), which was setup as part of the 'gcloud auth login' step.

**Comment by voellm** [comment]
Please let me know if this works for you.  Happy to help further.

**Comment by debabhatt** [comment]
Thank you for your attention to this matter & providing a quick  
response. I will discuss with my senior about your reply & will revert  
back when if required.


regards.








Quoting Anthony Voellm aka Tony the P3rfguy <notifications@github.com>:

**Comment by meteorfox** [comment]
OpenStack includes a service called Swift to provide an object storage as a service. I believe it can even emulate a subset of AWS S3 API. Perhaps support for this could be contributed to support such benchmark in OpenStack.

**Comment by meteorfox** [comment]
@voellm @debabhatt Can we close this issue? Support for OpenStack Swift has been merged for the OpenStack bindings. Please see PR #738 for more details.

**Comment by debabhatt** [comment]
Ok. sure , since support for Openstack Swift has been added ( as per PR #738 ) so we can  certainly close the issue. we may revert back again if any further issue arises in this regard. 

Thank you.

**Comment by meteorfox** [comment]
Thanks!
