### ISSUE TITLE
Refactor config.yaml to move all provider specific pieces into the provider directory

### ISSUE THREAD

**Issue by voellm** [GoogleCloudPlatform/PerfKitBenchmarker#704]
Today we have a single master config file
https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/tree/master/perfkitbenchmarker/configs 
that lists a default machine type per cloud.  This central file is a little hard to discover and creates a serialization point of changes for providers.

I'd like to refactor this file into one file per provider and leave any truly global config in config.yaml

@ehankland 
@mateusz-blaszkowski 
@meteorfox 

Thoughts?

**Comment by ehankland** [comment]
The single file makes it easy to define equivalence classes across clouds - for instance something we may want to do is make the default disks have the same number of advertised iops (rather than just being the same size). Having a file per provider would make it harder to do this since it will be less clear what the intent is if they are all in different places and defining a new "class" would mean editing |providers| files.

Additionally, the way the defaults are currently specified in default configurations are via YAML anchors (basically via references). Having the defaults in multiple locations would break this - we could do something to make this work, but it wouldn't be as simple as it is now.

All of that said, if moving to multiple files makes sense, then we can definitely work around any of those issues.

**Comment by voellm** [comment]
I did think about the equivalence classes but figured we could make this an
"output" from PKB like ./pkb.py --print_default_configs

**Comment by voellm** [comment]
@hildrum 
@cmccoy 

Adding a few others to comment.

**Comment by cmccoy** [comment]
I agree with @ehankland about the benefits of defining VM types next to one another.

**Comment by hildrum** [comment]
I agree with @ehankland.  I'd like to keep provider-specific info with the providers, but it sounds like yaml's limitations means this is more complex that just splitting up that file in the configs directory.

**Comment by voellm** [comment]
Sounds good... closing the issue.
