### ISSUE TITLE
Why are buckets for regional latency testing DRA?

### ISSUE THREAD

**Issue by zbjornson** [GoogleCloudPlatform/PerfKitBenchmarker#750]
(Another low-priority question/potential change proposal.) It's great that object_storage_service compares multi-region and regional buckets, but why is the regional bucket DRA? From about a dozen tests I can't find a consistent difference in performance, but it adds another variable.

**Comment by voellm** [comment]
@stfeng 
@noahl

**Comment by stfeng** [comment]
Great question! At the time when this benchmark was written, it was
required to use DRA storage class for GCS regional bucket, hence the code.
I think such restriction has just recently been removed, so we should
change our code accordingly.

I will be back in a few days and make such change, if you'd like to get
this sooner, please feel free to submit a pr after testing and
verification. @noahl should be able to do a code review and merge.

Thank you!

**Comment by zbjornson** [comment]
Thanks for the explanation. Would it be too disruptive/breaking to (1) remove the "regional ___" tests, (2) add a command-line option --bucket_location and (3) add a command-line option --storage_class? Last night I was editing the code to change the bucket location. The above changes would allow you to run the full benchmark (latency, throughput, consistency) for any class, any location. Right now it is hard-coded to US and us-central1 for GCS. I can make a PR for this if it would be an acceptable change.

**Comment by stfeng** [comment]
Yep, I think it's a good idea, but let's make sure we do the "add" steps
first (your points 2 and 3 below), and only do the removal step (your step
1) a few weeks after the new functionalities are merged and released. This
is typically what we do when we introduce a breaking change. (Removal of
the regional tests is a "breaking" change).

**Comment by noahl** [comment]
I already have code for making buckets in specific regions. We decided to hold off on merging because I didn't have time to do in-depth testing of the AWS endpoints. But seeing as we now have a request for it, I would like to merge at least the GCS and Azure bits. AWS is up to you.

@zbjornson this should make your life a little bit easier. My code would only solve your point 2. You would still have to add --storage_class yourself.

**Comment by noahl** [comment]
@zbjornson just talked offline with @stfeng . It will be easier if one person does the whole change. If you want to do it, you can use my code in #609 as a starting point. If you can wait, we have plans to work on a related change in Q1 of next year, which will include adding a `--storage_region` flag and could easily include a `--storage_class` flag as well.

**Comment by zbjornson** [comment]
Hello again! Great to see #609 has been merged, but it looks like the behavior for GCP is now to test standard-class in the hard-coded default location and only use the `storage_region` flag for the DRA test. Am I reading that right? https://github.com/GoogleCloudPlatform/PerfKitBenchmarker/pull/609/files#diff-6eaa1bb94259e2c7a82d65fb5786b7f0R868

Is adding `--storage_class` still on the roadmap? To summarize this thread, it seems best to me to ultimately remove the hard-coded DRA test, although this is breaking. I can work on a PR sometime...

**Comment by noahl** [comment]
@zbjornson The GCS test is a bit weird in that it always tests two buckets - a continental bucket and a regional bucket. The `object_storage_region` flag applies to the regional bucket. I agree that's a bit weird - ultimately I think there should be one bucket, and the storage class should be given by `--storage_class`. Feel free to file a bug to track that if you want. I'd be glad to assign it to myself.

Adding `--storage_class` is not only on the roadmap, but coming soon. You're welcome to make a PR, but I plan to do it within the next few weeks if you don't.

**Comment by stfeng** [comment]
@zbjornson The current behavior is the same as before: 1) test the "US" continentally replicated bucket with "standard" as the storage class, and 2) test regionally replicated bucket using DRA as storage class. The only change introduced by this PR is to introduce an *optional* parameter so people can specify which region they want to use for 2). 

Two further clarifications:

1. Using the DRA storage class was *required* for GCS regional bucket when this code was initially written, this restriction was just recently removed for some regional buckets (e.g., us-central1) but not all. Once such restriction is removed for all regional buckets, we should make a simple code change here to use the standard storage class rather than DRA for regional buckets.

2. @noahl - It's not wierd to test both standard bucket and regional bucket for GCS. This is because GCS is current the only provider that provides both a continental-based replication scheme and a regional-based replication scheme. Benchmarking the regional performance yields results that are comparable to other providers who are regional-based only. Benchmarking the continentally replicated performance provides useful information for users who want to evaluate GCS and gives them the complete picture without requiring them to run this benchmark twice, and continentally replicated bucket is still quite popular among GCS users. 

As usual, we'd be happy to re-evaluate when things change in the future, e.g., when DRA requirements are completely removed from GCS regional buckets, and/or when regional buckets become more popular among gcs users (such that no one cares about continental buckets any more), at which point, we can make corresponding adjustment.

**Comment by noahl** [comment]
@stfeng I think you explained that to me before; I'm sorry I didn't
remember it.

I think when I was making #609 I should have let the
`object_storage_region` flag change the continent of the continental bucket
to match the region, but I didn't realize how it worked at the time. Does
that sound reasonable to you?

**Comment by zbjornson** [comment]
Thank you both for the comments.

@stfeng re: (2), I actually think it *is* weird because the regional bucket is only tested for latency (one byte RW), but not throughput or consistency like the multi-region bucket. I ended up tweaking the code so that I could test throughput and consistency for regional buckets vs. multi-region. Likewise, I would like to see all three metrics for all three classes of storage.

In the same way that certain VM types are disallowed in certain zones (e.g. n1-standard-32 in us-central1-a), it seems reasonable to leave it up to the user to pick valid combinations of regions and classes (and not disallow n1-standard-32 altogether). As you said, the number of invalid combinations will be shrinking as well...

**Comment by stfeng** [comment]
The reason we are only doing latency tests for regional is because we
expected regional offering to differ from continental mainly in terms of
(write) latency only. The other two scenarios (throughput and consistency)
both take significantly longer to run and wouldn't reveal much more
additional information than one would have already got from the continental
tests. It is a concious trade-off decision.

With that said, I am open to the idea to allow users to choose a specific
<bucket location, storage class> combo as an override to the default
behavior. The bucket location is already (mostly) supported via the new
"storage region" flag. We do need to add the storage class support though.

Please file an issue so we can track the work and have
further discussions there.

Thank you for your input!

**Comment by zbjornson** [comment]
Issues created. Thanks for the feedback and all your work! :)
