### ISSUE TITLE
Outdated/broken image on Azure

### ISSUE THREAD

**Issue by yuyantingzero** [GoogleCloudPlatform/PerfKitBenchmarker#82]
PerfkitBenchmarker has not updated its images used by vms for a while, causing some software installation problems, especially on Azure.

When trying to install openjdk-7-jdk, I get following errors.

2015-01-27 17:26:36,504 ERROR    Got exception running InstallPackages: Got non-zero return code (100) executing sudo DEBIAN_FRONTEND='noninteractive' /usr/bi
n/apt-get -y install openjdk-7-jdk
Full command: /usr/bin/ssh -A -p 22 perfkit@191.237.18.89 -2 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PreferredAut
hentications=publickey -o PasswordAuthentication=no -o ConnectTimeout=5 -o GSSAPIAuthentication=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10 -i /tmp
/perfkitbenchmarker/run_fdf1048d/perfkitbenchmarker_keyfile sudo DEBIAN_FRONTEND='noninteractive' /usr/bin/apt-get -y install openjdk-7-jdk
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 openjdk-7-jdk : Depends: openjdk-7-jre (= 7u71-2.5.3-0ubuntu0.14.04.1) but it is not going to be installed
                 Recommends: libxt-dev but it is not installable
STDERR: Warning: Permanently added '191.237.18.89' (ECDSA) to the list of known hosts.
E: Unable to correct problems, you have held broken packages.

**Comment by voellm** [comment]
What's the next step here?

**Comment by timothyeharris** [comment]
I'm running into this exact same issue, and it's causing the Hadoop test to fail.  I'm having a similar problem with the block_storage benchmark saying : 

"Package libaio1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

STDERR: Warning: Permanently added '23.99.192.174' (ECDSA) to the list of known hosts.
E: Unable to locate package libaio-dev
E: Package 'libaio1' has no installation candidate"

In the case of open-jdk, I manually created a VM using the same image you're using and manually walked through the apt-get update and apt-get install commands, and the open-jdk package installed successfully --- is there anything different (permissions or path?) about remote installation via SSH command vs. interactive installation in a terminal window? 

(Right now I'd characterize this as a bug rather than an enhancement)

**Comment by yuyantingzero** [comment]
I do not think this problem is caused by remote SSH. I remember when I first caught this bug, I log into the VM and try to install manually and the problem still exists.
Also I do think it happens only on some of the vms, as in the third thread, I tried cassandra_stress with 4 exactly same vms, 2 succeed, but the other 2 failed with this package installation problem.

**Comment by timothyeharris** [comment]
yuyantingzero, what image/machine-type are you attempting to run against?

I was trying to run Hadoop Terrasort on an A7 machine type in US Central.  The image PKB selected was "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-14_04_1-LTS-amd64-server
 -20150123-en-us-30GB"

If the results are inconsistent, that would indicate some sort of inconsistency in copies of the VHDs...

**Comment by yuyantingzero** [comment]
I ran against default image/machine-types. Image: "b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu14_04_1-LTS-amd64-server-20150123-en-us-30GB" , machine type: A1 (Small in PKB).

@timothyeharris , does all of the vms in hadoop test failed to retrieve the package? The hadoop tests creates 9 vms.

**Comment by yuyantingzero** [comment]
Work around is to installing the necessary package manually, I will be writing a fix for this.

**Comment by yuyantingzero** [comment]
@timothyeharris do you mind opening another issue to track fio, block_storage_benchmark? I will fix the open-jdk bug in this release, but do not have enough time for the fio block_storage_benchmark.

**Comment by yuyantingzero** [comment]
Fix in dev. According to @ehankland , Azure seems to improve their repository servers recently. After a few retries, even without replacing the sources.list, it still succeeds. But I will leave the fix as it is, and remove it when apt-get install openjdk-7-jdk succeeds without retrying.
